Vagrant.configure("2") do |config|
# virtual machine configuration
config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    v.auto_nat_dns_proxy = false
    v.customize ["modifyvm", :id, "--natdnsproxy1", "off" ]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "off" ]
end

# using ubuntu host
config.vm.box = "ubuntu/trusty64"

config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

#use rsycn to keep host in sync with guest VM
config.vm.synced_folder ".", "/sync", type: "rsync",
    rsync__exclude: ".git/",
    rsync__exclude: "node_modules/"

# provision with docker and docker-compose
  config.vm.provision :docker

# when running docker compose always rebuild and run
  config.vm.provision :docker_compose, yml: "/sync/docker-compose.yml", rebuild: true,
    options: "--x-networking", command_options: { rm: "", up: "-d --timeout 50"}, run: "always"

# don't automatically start syncing,
# we'll kick that off in the startup script
  config.gatling.rsync_on_startup = false

#forward ports
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.18.11"
end

